wish: wish.o readline.o command.o error.o
	gcc -o wish wish.o readline.o command.o error.o

wish.o: wish.c
	gcc -c wish.c

readline.o: readline.c
	gcc -c readline.c

command.o: command.c
	gcc -c command.c

error.o: error.c
	gcc -c error.c

